# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: someip2val-build

on:
  pull_request:
    paths:
      - ".github/workflows/someip2val_build.yml"
      - "someip2val/**"
  workflow_dispatch:

jobs:
  build:
    # reduce runtime requirements from ubuntu, ubuntu-18.04 fails for aarch64
    runs-on: ubuntu-20.04
    name: Build
    strategy:
      matrix:
        target-arch: [x86_64, aarch64]
      fail-fast: true

    steps:
      - name: Install Pre-requisities
        run: |
          sudo apt-get update -qqy && \
          sudo apt-get install -qqy --no-install-recommends \
              cmake g++ build-essential \
              g++-aarch64-linux-gnu binutils-aarch64-linux-gnu \
              jq python3 python3-pip python3-setuptools &&
          pip3 install -U conan

      - name: Checkout
        uses: actions/checkout@v3

      - name: Run build
        working-directory: ${{github.workspace}}/someip2val
        run: ./build-release.sh ${{ matrix.target-arch }}

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: someip2val_${{ matrix.target-arch }}_release
          path: |
            ${{github.workspace}}/someip2val/target/${{ matrix.target-arch }}/release/install/bin
            ${{github.workspace}}/someip2val/target/${{ matrix.target-arch }}/release/install/lib/libvsomeip*.so.3
          if-no-files-found: error

  build_docker:
    # reduce runtime requirements from ubuntu, ubuntu-18.04 fails for aarch64
    runs-on: ubuntu-20.04
    name: Build docker
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/someip-feeder
          tags: |
            type=sha
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=edge
            type=raw,value=latest,enable={{is_default_branch}}

      - name: "Build image"
        id: image_build
        uses: docker/build-push-action@v3
        with:
          pull: false
          push: true
          file: ./someip2val/Dockerfile
          context: "./someip2val"
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
